name: production
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 2.7
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - run: bundle exec rspec spec
      - uses: actions/cache@v3
        with:
          key: "translation-and-audio"
          path: |
            generators/cache
      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          create_credentials_file: true
      - run: bundle exec ./generators/dictionary-update
      - run: bundle exec ./generators/audio-update
      - run: bundle exec ./generators/audio-upload
