name: production
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-20.04
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 2.7
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - run: bundle exec rspec spec
      - uses: actions/cache@v3
        with:
          key: "translation-and-audio"
          path: |
            generators/cache
      # enable ssh to the build
      # - uses: lhotari/action-upterm@v1
      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
      - run: bundle exec ./generators/dictionary-update
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - uses: FedericoCarboni/setup-ffmpeg@v1
      - run: bundle exec ./generators/audio-update
      - run: bundle exec ./generators/audio-upload
